server:
    port: 8888
    context-path: /sample-app
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:9999/auth/oauth/token
      userAuthorizationUri: http://localhost:9999/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:9999/auth/sso/me
spring:
  thymeleaf:
    cache: false        